const Social = require("../../structures/Social.js");

class Dice extends Social {

  constructor(...args) {
    super(...args, {
      name: "dice",
      description: "Rolls a 6-sided dice once unless specified",
      category: "4. Fun",
      usage: "dice [rolls] [dice sides]",
      extended: "This returns a random number generated by rolling a x-sided dice x times (rolls a 6-sided dice once if given no argument)",
      cost: 5,
      cooldown: 10,
      aliases: []
    });
  }

  async run(message, args, level) { // eslint-disable-line no-unused-vars
    const response = await message.channel.send(`${message.client.responses.loadingMessages.random().replaceAll("{{user}}", message.member.displayName)}`);

    try {
      const rolls = (args[0] === undefined) ? 1 : args[0];
      const sides = (args[1] === undefined) ? 6 : args[1];
      if (rolls > 100000 || sides > 100000)
        response.edit("Those numbers are just too high so how about no?");
      else {
        let total = 0;
        for (let i = 1; i <= rolls; i++) {
          const number = Math.floor(Math.random() * sides) + 1;
          total += number;
        }
        const average = Math.floor((total / rolls));
        response.edit(`Requested by **${message.author.tag}** ❯ \`${message.content}\` | You rolled a ${sides}-sided dice ${rolls} times! The total is **${total}** (Average: **${average}**)`);
      }
    } catch (error) {
      await response.edit(`${message.client.responses.errorMessages.random().replaceAll("{{user}}", message.member.displayName)}`);
      message.client.console.error(error);
    }
  }
}

module.exports = Dice;
