const Social = require("../../structures/Social.js");
const { MessageEmbed } = require("discord.js");
const { get, post } = require("snekfetch");

class IsNowIllegal extends Social {

  constructor(...args) {
    super(...args, {
      name: "illegal",
      description: "Returns Trump making something illegal",
      category: "4. Fun",
      usage: "illegal [text]",
      extended: "Powered by IsNowIllegal.com, get Donald Trump to make anything illegal.",
      cost: 15,
      cooldown: 10,
      aliases: ["trump", "sign"],
      botPerms: ["EMBED_LINKS"]
    });
    this.inUse = null;
  }

  cmdVerify(message, args, response) {
    if (this.inUse) return Promise.reject(new this.client.methods.errors.APIError("Trump is currently making something illegal, please wait.", response));
    const word = args.join(" ");
    if (word.length < 1 || word.length > 10) return Promise.reject(new this.client.methods.errors.UsageError("Cannot be longer than 10 characters or shorter than 1 character.", response));
    const wordMatch = /^[a-zA-Z\s]{1,10}$/.exec(word);
    if (!wordMatch) return Promise.reject(new this.client.methods.errors.UsageError("oops! Non-standard unicode characters are now illegal.", response));
    return Promise.resolve(word);
  }

  async run(message, args, level) { // eslint-disable-line no-unused-vars 
    const response = await message.channel.send(`${message.client.responses.loadingMessages.random().replaceAll("{{user}}", message.member.displayName)}`);

    try {
      const word = await this.cmdVerify(message, args, response);
      this.inUse = message.author.id;
      await post("https://is-now-illegal.firebaseio.com/queue/tasks.json").send({ task: "gif", word: word.toUpperCase() });
      const { body } = await get(`https://is-now-illegal.firebaseio.com/gifs/${word.toUpperCase()}.json`);
      this.inUse = null;
      
      const embed = new MessageEmbed()
        .setDescription(body.url)
        .setColor(message.client.config.colors.random())
        .setImage(body.url)
        .setFooter("FaiyaShisutazu", message.client.user.displayAvatarURL({ format: "png", size: 32 }))
        .setTimestamp();
      
      await response.edit(`Requested by **${message.author.tag}** ❯ \`${message.content}\` | Generated by isnowillegal.com`, embed);
    } catch (error) {
      await response .edit(`${message.client.responses.errorMessages.random().replaceAll("{{user}}", message.member.displayName)}`);
      message.client.console.error(error);
    }
  }
}

module.exports = IsNowIllegal;